templates/_helpers.tpl
templates/auth/auth.yaml
templates/cmdesc/cmdesc.yaml
templates/configdb/configdb.yaml
templates/directory/directory-mqtt.yaml
templates/dumps.yaml
templates/identity/krb-keys-operator.yaml
templates/identity/krb5-conf.yaml
templates/identity/rbac.yaml
templates/manager/env/manager-config.yaml
templates/mqtt/mqtt.yaml

This is the version of the helm chart currently running on my dev cluster, that `edge` and `git` are deployed over the top of.

Helm changes needed for the Edge Deployment operator

---

templates/auth/principals/operators.yaml
templates/auth/principals/service-clients.yaml
templates/auth/principals/services.yaml

Excessive chomping on Helm templates was causing the YAML divider `---` to end up appended to the end of the previous line.

Fix some invalid generated YAML.

---

crds/kerberos-keys-crd.yaml
crds/kubegres-crd.yaml

It appears as though Helm control structures can't be used outside the templates directory (unsurprisingly!), so we can't apply them to the CRDs.
@amrc-benmorrow this may cause issues if the CRD already exists on a cluster.

Remove code to conditionally apply CRDs

---

templates/auth/principals/service-clients.yaml
values.yaml

Pull fixed versions of the images rather than always pulling `latest`.
Different versions of the images will need different deployment configuration. This means a given version of the Helm chart has to pull fixed image versions.

Fix versions in values.yaml.

---

README.md
values.yaml

Updated README.md and values.yaml to discourage using localhost as the default baseUrl and domain. Using localhost comes with many issues and it's often simpler to configure a production-like environment instead.

Update README and values.yaml

---

.github/workflows/publish-helm.yml

This commit modifies how the Helm package version is formatted in the GitHub actions workflow for publishing Helm charts. The change ensures that the 'v' prefix is stripped from the version tags. This conforms to the SemVer norm, thus maintaining consistency and compatibility with third-party tools expecting this standard format.

Update Helm tag version format

---

README.md

Explicitly state `--version ^2.0.0` when installing to ensure that the latest non-breaking version of the chart is installed.

Add semver range to installation readme

---

templates/auth/principals/service-clients.yaml
templates/auth/principals/services.yaml
templates/edo/dumps.yaml
templates/edo/edge.yaml
values.yaml

Adjusted the EDO to use more specific names and modified the service account names to reflect a clearer role. Added verbosity value for EDO, change to integrate with the logging level. Fixed the 'edge-keytabs' to be 'edo-keytabs' as required. Added 'edo/dumps.yaml', a script for dumping pre-seed required aces, groups, principals and ConfigDB resources. Also changed the principal names to be more identifiable. These modifications make the EDO easier to identify and configure, and meet the appropriate security requirements.

Add Edge Deployment Operator (EDO) Auth & ConfigDB seeds

---

crds/kerberos-keys-crd.yaml
templates/auth/principals/service-clients.yaml
templates/auth/principals/services.yaml
templates/dumps.yaml
templates/edo/dumps.yaml
templates/edo/edge.yaml
templates/edo/ingress.yaml
templates/git/git.yaml
values.yaml

This gets the git and EDO deployments into a working state.
There is one significant remaining problem: the initial creation of the git repos, and the fact that the repo UUID for the `shared/flux-system` repo needs to be hardcoded into the cluster creation template. This will require changes to the git server code, I think.
This updates the KerberosKey CRD. I don't think we yet have an upgrade strategy here; possibly this will have to be another major release of ACS with (another) manual upgrade step.

Fix the EDO deployment

---

templates/auth/middleware/basic-auth-middleware.yaml

Updated the basic-auth-middleware.yaml file to enable conditional configuration of the Traefik middleware. This change helps to ensure the middleware is set up only when .Values.traefik is enabled, preventing a `resource mapping not found` error.

Enable conditional Traefik middleware configuration

---

templates/warehouse/influxdb-ingester.yaml
values.yaml

The value for the `LOG_LEVEL` in the `influxdb-ingester` configuration was hardcoded to `info`. This change replaces it with a value from `Values.warehouse.ingester.logLevel` making it configurable. With this change, we can easily modify the `LOG_LEVEL` without altering the codebase, just by changing a value in the environment configuration.

Update logLevel in influxDB ingester to a configurable value

---

templates/identity/kdc.yaml
values.yaml

Add a values.yaml setting to make the kdb-init container sit and wait instead of proceeding with KDB setup. This allows an administrator to perform a manual restore from backup before the KDC starts up.

Allow manual setup of the Kerberos KDB.

---

Chart.lock
Chart.yaml

This commit introduces an alias for the Switchboard chart within the Chart.yaml file. Additionally, an updated digest and timestamp in the Chart.lock file indicate that it has been regenerated, presumably as a part of this change. This brings more clarity and organization to the helm charts.

Update Switchboard chart and regenerate lock file

---

Chart.lock
Chart.yaml

The repository paths for 'switchboard' in Chart.lock and Chart.yaml files have been updated. The change resulted in the removal of 'charts/' from all repository URLs and in updates to the 'digest' and 'generated' fields in Chart.lock. It seems the previous path was directing to an incorrect or non-existent location, and hence the paths were corrected to point to the right locations.

Update repository paths for switchboard in Chart.lock and Chart.yaml

---

values.yaml

Applied 'Recreate' deployment strategy type to the Grafana configuration in `values.yaml`. This update ensures that any change in the configuration would trigger a fresh deployment, replacing the previous version completely.

Update deployment strategy in Grafana configuration

---

values.yaml

v1.0.7 of the Manager includes a fix to config generation that ensures that edge agents have all they need to properly create the `is_transient` state.

Update the Manager to v1.0.7

---

templates/manager/redis.yaml

Set redis to recreate to prevent Longhorn from trying to mount the volume to two pods.

Redis recreate strategy

---

templates/auth/principals/service-clients.yaml
templates/mqtt/mqtt.yaml
values.yaml

These changes will only function with the new plugin (my open PR).
I think perhaps the chart should pull in fixed versions of the components, rather than `:latest`? We maybe also need a policy about whether a change to the required configuration is a semver major, minor or patch change.
We need an image that contains `k5start`, and ideally a Kerberised `curl` too. Currently I've pulled `factoryplus-shell` from the internal registry, but I don't think that's the right answer, so this is currently draft.

Updates to support the new HiveMQ plugin.

---

templates/mqtt/mqtt.yaml
values.yaml

* Pull in the latest version of the HiveMQ plugin, which will log in to Kerberos again as needed to keep its TGT up to date.
* Remove k5start from the HiveMQ deployment and give HiveMQ access to its own client keytab.
This should fix the issues with MQTT falling over every 10 hours.

Keep HiveMQ's TGT up to date

---

templates/identity/kdc.yaml

In order for krbkeys operators on the edge to do their job they need write access to kadmin. Limit this access be requiring, by convention, that all principals controlled by the krbkeys operator on a particular cluster have the name of the cluster as their second part.

Give the edge krbkeys kadmin permissions

---

templates/dumps.yaml

The previous version of the file had misplaced commas in the object definitions in "dumps.yaml" template. This commit fixes the syntax by correctly placing commas at the end of each object in the array.

Fix the syntax error in dumps.yaml template file

---

templates/_helpers.tpl
templates/auth/auth.yaml
templates/cmdesc/cmdesc.yaml
templates/configdb/configdb.yaml
templates/directory/directory-mqtt.yaml
templates/directory/directory-webapi.yaml
templates/edo/edge.yaml
templates/git/git.yaml
values.yaml

* The cache expiration time on the service responses is much too short for production. Adjust it to something longer, and configurable.
* Avoid running commands with `npm run`. This fails to pass SIGTERM down to its child which is causing pods to fail to exit properly.
This needs cherry-picking to v2-stable.

Tweaks for better production behaviour

---

templates/_helpers.tpl
templates/dumps.yaml
templates/edo/edge.yaml
templates/identity/kdc.yaml
templates/service-setup.yaml
values.yaml

This is capable of configuring an edge cluster centrally from a ConfigDB entry, and can produce a bootstrap script to perform the edge steps of the bootstrap.
This PR **does not** include the proposed `edo` -> `clusters` renaming.
This version of the EDO requires ConfigDB entries that are not deployed by this PR. They will be deployed by a new version of acs-service-setup as they require per-deployment UUIDs.
Bootstrapping a cluster from the edge requires credentials for an admin account with kadmin rights. Using the `admin` account for this is not sensible, so, for now, allow kadmin ACLs to be configured from the values file.
Deploying this with no values changes requires a released version of the edge-helm-charts repo, to come shortly.

Deploy the new EDO

---

templates/postgres/postgres.yaml
values.yaml

The version of Postgres we were using has a security vulnerability. Upgrade to the latest release of version 14.
Make the image configurable from the values file.

Update Postgres version

---

values.yaml

(cherry picked from commit 48866ed8d5060dd263ae6c004c5d26c926a1a70d)

Fix InfluxDB PDB enabled typo

---

templates/cmdesc/cmdesc.yaml
templates/directory/directory-mqtt.yaml
templates/directory/directory-webapi.yaml
templates/identity/kdc.yaml
templates/identity/krb-keys-operator.yaml
templates/manager/cron.yaml
templates/manager/manager.yaml
templates/manager/queue.yaml
templates/manager/schema-import-cron.yaml
templates/mqtt/mqtt.yaml
templates/warehouse/influxdb-ingester.yaml

This is needed for offline cluster scenarios.
This is a backport of #113.

Include pullSecrets on all images

---

deploy/templates/_helpers.tpl
deploy/templates/identity/kdc.yaml
deploy/templates/manager/cron.yaml
deploy/templates/manager/manager.yaml
deploy/templates/manager/queue.yaml
deploy/templates/manager/schema-import-cron.yaml
deploy/templates/warehouse/influxdb-ingester.yaml
deploy/values.yaml

Use the helper function to use the chart version for the image tags if not specified in the values file.
- Replaced all remaining static calls to images with the helper functions.

Use chart version for images

---

acs-git/lib/status.js

Otherwise if we miss a ConfigDB MQTT update we'll never know.

git: Re-fetch config every 10 minutes

---

deploy/templates/_helpers.tpl
deploy/values.yaml

This will only function correctly for Helm charts published to Github Pages. Installing from a checkout or a git repo will need a `defaultTag` override.

Fix the image tag defaulting to chart version

---

acs-git/Makefile
acs-git/lib/auto-pull.js

Auto-pull on a git repo was failing when the repo did not already exist.

Create a git repo on auto-pull

---

deploy/Chart.lock
deploy/Chart.yaml
deploy/templates/lets-encrypt/tls.yaml
deploy/values.yaml
docs/installation.md

This update introduces support for automatic certificate generation in the Kubernetes deployment using Let's Encrypt and cert-manager. The application now includes a new setting, `acs.letsEncrypt.enabled`, which enables or disables this feature. Additionally, the installation instructions are updated to reflect these changes.

Add support for automatic Let's Encrypt certificate generation

---

ReleaseNotes.md
acs-service-setup/dumps/admin.yaml
acs-service-setup/lib/fixups.js
acs-service-setup/lib/helm.js
acs-service-setup/lib/service-setup.js
acs-service-setup/lib/uuids.js
deploy/templates/NOTES.txt
deploy/templates/auth/auth.yaml
deploy/templates/auth/principals/operators.yaml
deploy/templates/configdb/configdb.yaml
deploy/templates/dumps.yaml
deploy/templates/service-setup.yaml

* Move grants for admin@ into service-setup.
* Allow krbkeys to generate an installation-specific UUID instead of using a fixed one.
* Move the password into a dedicated Secret.
* Replace the Global Debugger role with a Global Debuggers user group.
Start a Release Notes document documenting the user-visible changes.
Closes: #230

Tidy up admin account creation

---

acs-edge-monitor/lib/monitor.js
acs-edge-monitor/lib/node.js
acs-edge-monitor/lib/sparkplug.js
mk/acs.k8s.mk

Using UUIDs for Sparkplug Device names is convenient, because we always have the UUID available, but it results in some very opaque addresses. Use the Node name instead, which means we can't publish to a Device until we've looked up an address for the monitored Node, but we don't have any useful information until then anyway.
Closes: #239

Use Node names for Monitor devices

---

acs-activity-monitor/Dockerfile
acs-activity-monitor/package.json
acs-admin/package.json
acs-visualiser/package.json

The changes involve updating the @amrc-factoryplus/service-client version to ^1.3.5 in both acs-activity-monitor and acs-visualiser. This eliminates the need for the line in the activity monitor Dockerfile as the underlying bug is now fixed upstream.

Update @amrc-factoryplus/service-client version

---

acs-activity-monitor/Dockerfile

In the Dockerfile, the base image has been changed from Nginx to Node.js. The configuration files specific to Nginx have been removed and replaced with 'serve', a simple Node.js static file server. This removes the overhead of having to configure Nginx for a simple static file serving scenario.

[Activity Monitor] Switch from Nginx to Node.js serve

---

deploy/templates/NOTES.txt

A new line was added to the NOTES.txt template, introducing the Activity Monitor link.

Add Activity Monitor to NOTES.txt template

---

acs-cmdesc/lib/cmdescd.js
acs-cmdesc/lib/mqttcli.js

There are situations where it is useful to know the identity of the principal who requested a CMD. Include this information in the CMD packet in the following form:
* The `uuid` field of the CMD is set to the Factory+ UUID.
* The `body` of the CMD is a UTF-8 string starting with a scheme name and a colon.
* The scheme `uuid:` is followed by a principal UUID in canonical string form.
* The scheme `kerberos:` is followed by a Kerberos principal name.
* The schema `sparkplug:` is followed by a Sparkplug address in `Group/Node` form.
(Currently Devices are not permitted to request command escalation, as they aren't security principals and can't be authorised.)
Closes: #268

Include requesting principal in CMDs

---

acs-edge/package-lock.json
acs-edge/package.json

Upstream version 4.0.14 appears to have a bug.

Lock down @types/readable-stream

---

acs-edge/docs/edge-split.md

Define a protocol for communication between the Edge Agent and drivers.
This runs over MQTT, with the EA serving as broker. The topic structure is defined by the protocol; this is not a generic MQTT driver. The protocol allows the EA to poll the driver, and also allows the driver to produce data asynchronously.

Create a spec for the edge agent split

---

influxdb-sparkplug-ingester/lib/mqttclient.ts

This PR fixes metric timestamps not being used in Influx.
- Now uses metric timestamp instead of Influx insertion timestamp.

Fixed Incorrect metric timestamp on Influx Ingester

---

ReleaseNotes.md
acs-service-setup/dumps/admin.yaml
acs-service-setup/lib/fixups.js
acs-service-setup/lib/helm.js
acs-service-setup/lib/service-setup.js
acs-service-setup/lib/uuids.js
deploy/templates/NOTES.txt
deploy/templates/auth/auth.yaml
deploy/templates/auth/principals/operators.yaml
deploy/templates/configdb/configdb.yaml
deploy/templates/dumps.yaml
deploy/templates/service-setup.yaml

* Ensure each ACS installation has a unique UUID for the `admin` principal.
* Move the `admin` password into a dedicated secret.
* Remove permission groups in favour of user groups.
* Create a Release Notes document documenting these changes for users.
The release notes document will need to be updated before cutting a release to ensure any changes users should be aware of are documented.

Tidy up some authentication details

---

deploy/templates/auth/auth.yaml
deploy/values.yaml

Default to not showing `query`, `service` or `token` logs, too.

Allow auth verbosity to be set in values.yaml

---

acs-service-setup/dumps/edge.yaml
acs-service-setup/lib/helm.js

We don't yet have a system for granting dynamic MQTT permissions which actually works. For now just grant the monitor global debugger rights.

Give the central monitors global debugger

---

deploy/templates/admin/ingress.yaml

This helps when the TLS certificate for the ACS installation does not include the base domain.

Also host admin interface at admin.*

---

ReleaseNotes.md

The release notes were adjusted to make the instructions about role removal more explicit. The role's access control entries should be removed and the role itself as well, as detailed in the updated documentation.

Clarify role removal instructions in release notes

---

acs-directory/api/openapi.yaml

Include the Links API. Remove the alpha note on the Alerts API; we're committed to the API now, at least for /v1.

Update Directory OpenAPI spec

---

acs-edge-sync/lib/deployments.js

It was originally supposed to be possible to specify `values.yaml` overrides in a _Edge deployment_ ConfigDB entry, avoiding the need to create a new _Helm chart template_ for every combination of values. This has never worked correctly; fix it.
Where an _Edge deployment_ deploys more than one chart, this will apply the same values overrides to them all. This is unlikely to be useful. We should consider deprecating multi-chart deployments altogether; they were intended for edge agent driver deployments, which can be handled in the edge-agent chart directly.

Fix deployment-specific values

---

acs-krb-keys-operator/crd/local-secret.yaml
acs-krb-keys-operator/lib/amrc/factoryplus/krbkeys/__init__.py
acs-krb-keys-operator/lib/amrc/factoryplus/krbkeys/event.py
acs-krb-keys-operator/lib/amrc/factoryplus/krbkeys/spec.py
acs-krb-keys-operator/lib/amrc/factoryplus/krbkeys/util.py

Give the krbkeys operator the ability to create secrets which only exist on an edge cluster, not connected to a Kerberos principal. These can be used to authenticate edge drivers to the edge agent.
Request these secrets using a new LocalSecret CRD.

Create local secrets with krbkeys

---

edge-helm-charts/charts/edge-agent/templates/_helpers.tpl
edge-helm-charts/charts/edge-agent/templates/edge-agent.yaml
edge-helm-charts/charts/edge-agent/templates/service.yaml
edge-helm-charts/charts/edge-agent/values.yaml
edge-helm-charts/charts/edge-cluster/crds/local-secret.yaml
edge-helm-charts/charts/edge-cluster/templates/krb-keys.yaml

Deploy Edge Agent drivers from within the edge-agent chart. There is no need for a separate chart as drivers all deploy identically.
At the moment the drivers deploy as containers on the edge agent pod. This keeps things simple and a bit more secure and means on-cluster drivers can contact the edge agent on `localhost` without needing to go through a Service.
If `externalIPs` is included in the values then the driver interface will be available externally to support off-cluster drivers. Authentication for such drivers will need to be handled through SealedSecrets and may need a little more work.

Deploy drivers via the edge Helm charts

---

edge-helm-charts/charts/node-red/templates/node-red.yaml
edge-helm-charts/charts/node-red/values.yaml

Give the node-red chart a list of `hostPath` mounts to grant to node-red. This is intended for mounting devices used to access external hardware. Obviously this needs to be used very carefully.

Allow node-red chart to map in devices

---

edge-helm-charts/charts/edge-agent/templates/_helpers.tpl
edge-helm-charts/charts/edge-agent/templates/edge-agent-key.yaml
edge-helm-charts/charts/edge-agent/templates/edge-agent.yaml
edge-helm-charts/charts/edge-agent/templates/service.yaml
edge-helm-charts/charts/edge-agent/values.yaml

Some device drivers necessarily need to access devices on the host. Allow the edge agent chart to map host devices into the driver containers.
Rework the edge agent k8s resource naming to use the node name instead of the UUID. The UUIDs are just getting annoying.

Allow drivers to access devices on the host

---

edge-helm-charts/charts/edge-agent/templates/edge-agent.yaml
edge-helm-charts/charts/edge-agent/values.yaml
edge-helm-charts/charts/node-red/templates/node-red.yaml
edge-helm-charts/charts/node-red/values.yaml

Containers that need to access host devices, e.g. serial ports, need to be run with privilege. Otherwise k8s forbids access. This is obviously a big hammer and should only be used with care.

Allow privileged containers

---

.github/workflows/publish.yml

Unfortunately these really need to be build for ARM, which will make the builds longer.

Wire up driver images to the build

---

acs-manager/resources/js/components/General/DeviceConnectionForm.vue

The 'Defined by Protocol' option is not valid for Drivers, but that's true of existing device types too (e.g. MQTT).

Drivers need payload type selection

---

acs-edge/Makefile
mk/README.md
mk/acs.docker.mk

Use of buildx appears to be mandatory now. Even an explicit `docker builder build` seems to invoke buildx. Adjust the Makefile to suit; this means the `build` target now performs `push`, and we need `pull` target for cases where we want an up-to-date local image.
Support multi-platform builds, now we can.

Change Makefiles to use docker buildx

---

edge-bacnet/lib/bacnet.js

This is a hack until we can fix the upstream edge agent bug sending 'undefined'.

Fix addr parsing handling 'undefined'

---

acs-visualiser/public/mqttclient.js
acs-visualiser/public/vis.js

There is a bug in the rendering when a node switches from 6 to 5 children and stops being rendered as an overflow node.
This is being triggered more often now as the temporary CMD nodes are included in the overflow count. This is incorrect but harder to fix.

Fix vis rendering when a node loses children

---

acs-edge/lib/helpers/typeHandler.ts

The Sparkplug specification requries all timestamps to be in milliseconds. This converts them if they are in seconds.

Fix inherited timestamps sometimes being in seconds since epoch

---

acs-edge/lib/devices/S7.ts
acs-edge/lib/helpers/typeHandler.ts
acs-edge/package.json

Polling metrics with no defined address was leading to the polling of the address `"undefined"`. Since this is rarely a valid address some of the drivers now have hacks in place to ignore this specific address. Fix the problem at the root instead.

Fix polling of metrics with no address

---

acs-manager/.docker/Dockerfiles/Dockerfile
acs-manager/app/Domain/Nodes/Actions/CreateNodeAction.php
acs-manager/app/Http/Controllers/NodeController.php
acs-manager/app/Http/Requests/CreateNodeRequest.php
acs-manager/resources/js/components/General/DeviceConnectionForm.vue
acs-manager/resources/js/components/Nodes/NewNodeOverlay.vue
acs-manager/vite.config.js
acs-visualiser/public/mqttclient.js

* Allow Node names to include hyphens. With the identification of clusters and Groups it will be useful to have structure within a Node name.
* Adapt the visualiser to understand structured Node names.
* Request and record a human-readable name for a Node, to go in the ConfigDB Info entry. Currently this cannot be edited via the Manager.
* Remove the validation from DriverDetails, it is refusing to allow an empty object. This is a valid config for the edge-test driver.
* Pin oven/bin version in the Dockerfile; 1.1.30 is causing build problems.
* Make the build a little more usable.

Minor Manager changes

---

acs-edge/lib/device.ts
acs-edge/lib/sparkplugNode.ts
acs-manager/app/Domain/Devices/Actions/UpdateDeviceInformationAction.php
acs-manager/app/Domain/Devices/Resources/DeviceDetailResource.php
acs-manager/app/Domain/Nodes/Actions/UpdateEdgeAgentConfigurationForNodeAction.php
acs-manager/app/Http/Controllers/DeviceController.php
acs-manager/app/Http/Requests/UpdateDeviceInformationRequest.php
acs-manager/database/migrations/2024_10_08_144300_add_device_pubinterval.php
acs-manager/resources/js/components/Devices/DeviceEditorInformationTab.vue
acs-manager/resources/js/components/FormControls/Input.vue

Allow configuration of batch publishing from the Manager.
* Deprecate the `asyncPubMode`/`pubInterval` properties on the Node configuration. The Manager has no interface to configure the Node and it doesn't really make sense for this to be a whole-node option.
* Create UI to configure a new per-Device `pubInterval` property.
* Change the Edge Agent to honour this new configuration. Remove the `asyncPubMode` implementation, it wasn't usable in practice without Manager support.
* Stop publishing the Node metrics related to `asyncPubMode`. Publish a `Publish Interval` metric on the Device.
* Make the poll/publish interval metrics read-only. We have no way to persist config changes any more.

Configure batch publishing from the Manager

---

acs-service-setup/lib/service-setup.js
deploy/templates/service-setup.yaml
deploy/values.yaml

* Refactor the service-setup Job to allow an arbitrary list of containers to be run under the control of the Helm values file.
* Include a new step to deploy the schemas to the ConfigDB.

Deploy schemas via service-setup

---

acs-manager/app/Domain/Schemas/Actions/GetDeviceSchemasAction.php
acs-manager/resources/js/components/Schemas/SchemaBrowser.vue
acs-schemas/deploy/bin/find-schemas.js
acs-schemas/deploy/package.json

We can't retrieve Git timestamps in the monorepo as we don't have the Git history in the Docker context.

Fix the build in the monorepo

---

deploy/templates/historians/uns.yaml
deploy/values.yaml

Create an init container on the UNS historian to create the bucket for the UNS namespace because the init script didn't create the bucket on helm upgrade.

 Add Influx Init container

---

acs-configdb/Makefile
acs-configdb/bin/api.js
acs-configdb/bin/load-dump.js
acs-configdb/eslint.config.mjs
acs-configdb/lib/api-v1.js
acs-configdb/lib/auth.js
acs-configdb/lib/constants.js
acs-configdb/lib/etags.js
acs-configdb/lib/model.js
acs-configdb/lib/notify-v2.js
acs-configdb/lib/rx-util.js
acs-configdb/lib/special.js
acs-configdb/package-lock.json
acs-configdb/package.json
docs/notify-v2.md
mk/acs.js.mk

Specify a new change-notify interface. This abandons the idea of trying to send notifications over Sparkplug in favour of using a direct WebSocket connection to each service. Hopefully this will be more robust and will avoid the bootstrapping issues that turn up when we try to implement change-notify on the Auth service. This new interface uses the `notify/v2` path prefix to avoid conflict with the (probably now abandoned) `notify/v1` spec which is on the dyn-deploy branch.
The new interface runs entirely over a WebSocket connection, which is used to multiplex multiple subscriptions to sources of notifications. Each subscription returns a sequence of HTTP responses, equivalent to the client polling the REST interface and ignoring duplicate responses. This means that error responses such …

Implement a WS notify interface on the ConfigDB

---

acs-configdb/bin/api.js
acs-configdb/package.json
deploy/templates/configdb/configdb.yaml
deploy/values.yaml

Accept a Helm value to configure the size of request body accepted by the ConfigDB. We are hitting the limit with some large Edge Agent config files.

Make the ConfigDB body size limit configurable

---

acs-service-setup/dumps/helm.yaml
acs-service-setup/lib/helm.js
acs-service-setup/lib/uuids.js
edge-helm-charts/charts/mqtt-broker/Chart.yaml
edge-helm-charts/charts/mqtt-broker/templates/_helpers.tpl
edge-helm-charts/charts/mqtt-broker/templates/mqtt-broker.yaml
edge-helm-charts/charts/mqtt-broker/templates/service.yaml
edge-helm-charts/charts/mqtt-broker/values.yaml

Create a new edge helm chart which deploys an MQTT broker. This broker is exposed to the cluster as service; the chart also provides the option to expose it on an external IP.
No security is currently implemented, beyond a default of `internalTrafficPolicy: Local` which should prevent off-node pods from contacting the broker but is not intended as a security feature.

Create an edge MQTT broker helm chart

---

.github/workflows/helm-lint.yml
.github/workflows/publish.yml
acs-configdb/package-lock.json
acs-edge/package-lock.json
acs-edge/package.json
acs-service-setup/dumps/helm.yaml

Update build deps

---

historian-uns/src/mqttclient.ts

If an MQTT packet was received without custom properties, an exception was thrown. The added optional chaining prevents this error.

Fix UNS historian null reference

---

acs-auth/bin/sexpr.js
docs/auth.md
docs/auth/dyn-groups.md
docs/auth/sexpr.md

Specify the data model used for the new Auth service. This defines ACLs in terms of templates, allowing a single grant to expand to multiple related grants on different services. The template language is able to look up information from other services allowing support for dynamically-defined ACLs.

New Auth spec

---

acs-edge/lib/driverBroker.ts
edge-helm-charts/charts/edge-agent/templates/edge-agent.yaml
edge-helm-charts/charts/edge-agent/templates/local-secrets.yaml
edge-helm-charts/charts/edge-agent/values.yaml

Support deploying external drivers. For now the driver credentials will need to be retrieved from the Secret in the cluster.

Support external drivers

---

acs-edge/lib/devices/MQTT.ts
acs-edge/lib/helpers/typeHandler.ts

This commit makes the edge agent check for null and undefined paths. Previously, it only checked `''`, which didn't work because the manager keeps them as undefined by default.

Fix undefined path check for edge agent

---

acs-krb-keys-operator/Dockerfile

The source must be copied into the build.

Build python-kadmv correctly

---

deploy/templates/hooks/post-delete.yaml

Finalizers on custom resource definitions cause both the factory-plus namespace to be stuck in a terminating state. The added job runs on the helm post delete hook and patches the Kerberos Key to remove the finalizers. 
1. Run `Helm uninstall acs -n factory-plus`.
2. Wait for the job to complete.
3. Run `kubectl delete namesapce factory-plus` to delete the factory-plus namespace.
4. The namespace should delete and not be stuck in a terminating state.

Fix finalizers preventing namespace deletion

---

acs-configdb/lib/model.js

This is a bug introduced in e647cfa when changing the structure of config_get to match the other notification sources.

ConfigDB PATCH was destroying old content

---

deploy/templates/service-setup.yaml

Service setup previously run on helm post-install but services dependant on it would never run. This is fixed by removing the hook annotation and naming the job with a random string. The job runs on helm install and will run again on helm upgrade, terminating any previous running instance of the job.
1. Change /deploy/service-setup.yaml line 70 to command: `["/bin/sleep 1000"]` (this prevents the job from completing to test the job termination on helm upgrade).
2. Run:
`helm install acs <local repo path>/amrc-connectivity-stack/deploy --version 3.4.2 -f values.yaml --namespace factory-plus --wait --timeout 30m`
3. Wait for all service to be running and service-setup init containers to complete. 
4. Run:
`helm upgrade acs <local repo path>/amrc-connectivity-stack/deploy --version 3.4.2 -f …

Fix service-setup circular dependency

---

acs-auth/.gitignore
acs-auth/bin/authn.js
acs-auth/editor/editor.js
acs-auth/lib/api_v2.js
acs-auth/lib/authz.js
acs-auth/lib/dataflow.js
acs-auth/lib/model.js
acs-auth/lib/queries.js
acs-auth/lib/uuids.js
acs-auth/lib/validate.js
acs-auth/package-lock.json
acs-auth/package.json
acs-configdb/lib/model.js
acs-configdb/lib/notify.js
acs-service-setup/lib/auth-group.js
acs-service-setup/lib/service-setup.js
deploy/templates/service-setup.yaml

The v2 API implementation is driven by Rx rather than fetching from the database all the time. This will allow a notify/v2 interface to be implemented straightforwardly.
* Track the classes we need from the ConfigDB.
* Track grants from the database.
* Implement correct (limited) group expansion for ACLs, respecting the `plural` field.
* Provide ACL-fetching endpoints `v2/acl/:uuid` and `v2/acl/kerberos/:upn`.
* Provide endpoints to edit the grants.

Start the v2 API

---

deploy/templates/service-setup.yaml

After the init containers have finished MQTT needs to be restarted for the ACL changes to pull through. The added restart container restarts the MQTT deployment to fix this issue.
1. Create the factory-plus namespace and helm install acs.
2. All acs services should finish in a healthy state, mqtt shouldn't need to be restated.

Add MQTT restart container

---

deploy/templates/service-setup.yaml

If an error occurred during the restart of mqtt, the container would not restart. The added changes check if the restart was successful and retries if not.

Fix mqtt restart on failure

---

deploy/templates/service-setup.yaml

The service setup service account permissions did not account for the addition of deployment status checking causing the container to always exit with code 1. The added permissions fix the issue.

Fix incorrect service account permissions

---

acs-auth/lib/api_v2.js
acs-auth/lib/dataflow.js
acs-auth/lib/model.js
acs-auth/lib/queries.js
acs-auth/lib/validate.js
acs-configdb/lib/model.js
acs-krb-keys-operator/.gitignore
acs-krb-keys-operator/lib/amrc/factoryplus/krbkeys/__init__.py
acs-krb-keys-operator/lib/amrc/factoryplus/krbkeys/account.py
acs-krb-keys-operator/lib/amrc/factoryplus/krbkeys/event.py
acs-krb-keys-operator/lib/amrc/factoryplus/krbkeys/util.py
acs-krb-keys-operator/lib/amrc/factoryplus/service_client/auth.py
acs-krb-keys-operator/lib/amrc/factoryplus/service_client/configdb.py
acs-krb-keys-operator/lib/amrc/factoryplus/service_client/service_interface.py

This means pushing group memberships to the ConfigDB rather than the Auth service.
* Fix some bugs this turned up in the Auth service.
* When we have a new KerberosKey, look up the principal in the Auth service initially. This should mean we can respin an edge cluster without losing the edge account identities.
* Allow KerberosKeys to be suspended. This will be required to migrate `sv1git` from a static to a dynamic UUID.

Update krbkeys to the Auth v2 API

---

deploy/templates/coredns/traefik-redirect.yaml
deploy/values.yaml

The added coredns config map redirects all external URLs back to the internal Traefik service. This fixes issues caused by ACS instances which don't have external DNS setup.

Add Internal Traefik Redirect

---

Makefile
acs-service-setup/bin/check-yaml.js
acs-service-setup/lib/dumps.js
acs-service-setup/lib/service-setup.js
deploy/Makefile

The lint step now requires a valid ACS config. This means a fair amount of refactoring to allow the lint step to use a fake ACS config and get it into the loader configuration.
While we're here: create a top-level `lint` target, and include Helm chart linting. This could now reasonably by run before allowing a PR to be merged.

Fix service-setup linting

---

acs-directory/lib/queries.js
acs-directory/sql/migrate.sql
acs-directory/sql/v12.sql

Added a new SQL migration to the directory to make a services unique. This prevents multiple instances of the same service being registered.

Fix Helm Upgrade Failure

---

acs-auth/lib/api_v2.js
acs-auth/lib/authz.js
acs-auth/lib/queries.js
acs-cluster-manager/lib/actions.js
acs-cluster-manager/lib/clusters.js
acs-configdb/lib/mqttcli.js
acs-service-setup/dumps/clusters.yaml
acs-service-setup/lib/clusters.js
acs-service-setup/lib/helm.js
deploy/templates/configdb/configdb.yaml
lib/js-service-client/lib/service/auth.js
lib/js-service-client/lib/service/configdb.js
lib/js-service-client/lib/sparkplug/util.js
mk/acs.k8s.mk

Services which edit the auth information must be updated to use the new APIs.
* Update cluster-manger to the Auth v2 API.
* Change the POST v2/grant endpoint to allow exact duplicates and return 200.
* Create an endpoint to search for grants.
* Adjust ACLs to allow for groups being in the ConfigDB.
* Reenable the ConfigDB MQTT interface, cluster-manager relies on it for now.
* Allow the ConfigDB to start without MQTT, this is now important for bootstrapping.
The cluster-manager no longer has permission to mark objects deleted; this is now a PATCH to the _Registration_ entries and granting that would allow very broad changes. We need a ConfigDB change to allow ACLs to be applied to the individual changes made to the _Registration_ entry, but that is not straighforward to implement.

Fix cluster-manager

---

acs-service-setup/dumps/service-urls.yaml
acs-service-setup/lib/dumps.js
deploy/templates/service-setup.yaml

"domain" was renamed to "base_url", this caused the edge charts to have an undefined domain. Changing the name back to "domain" fixes the issue.

Fix incorrect acs config name

---

acs-directory/lib/mqttcli.js
acs-directory/lib/queries.js
historian-sparkplug/lib/mqttclient.ts
lib/js-service-client/lib/deps.js
lib/js-service-client/lib/sparkplug/util.js
uns-ingester-sparkplug/Dockerfile
uns-ingester-sparkplug/lib/mqttclient.ts
uns-ingester-sparkplug/package-lock.json
uns-ingester-sparkplug/package.json

We have a problem here: `sparkplug-payload` @1.0.1 and @1.0.3 have different APIs. 1.0.3 returns Longs for timestamps where 1.0.1 did not. `utilities` pulled in 1.0.1 in the past, `service-client` now pulls in `1.0.3`, and we're trying to update everything to use `service-client`. In particular `historian-sparkplug` was broken by this change.
Take a slightly radical approach: Longs are awful. Rather than continuing to hack around them let's just get rid of them. Supply a new method on `service-client`'s SpB object, `decodeToNative`, which decodes timestamps to Dates and aliases and 64bit values to native BigInts. This removes any need to mess about with `.toString()` as BigInts can be used as object or Map keys with no issues.
In the future we may want to look into removing …

Update for Sparkplug decoding API change

---

deploy/templates/service-setup.yaml
deploy/values.yaml

This pull request includes changes to the deployment configuration to support loading schemas into the ConfigDB and to add environment variables for the new container. The most important changes include adding a new container configuration in the `service-setup.yaml` file and updating the `values.yaml` file to include schema loading settings.
* [`deploy/templates/service-setup.yaml`](diffhunk://#diff-9ce0a162b5f64bc5b7f641da3e8ec49cdd2f354d03b6cf8cc8718195a3c95f24R126-R141): Added a new container configuration for loading schemas, including environment variables such as `DIRECTORY_URL`, `SERVICE_USERNAME`, `SERVICE_PASSWORD`, and `VERBOSE`.
* [`deploy/values.yaml`](diffhunk://#diff-c59120ea9e7b09fe13ee02876552a043f9f0c4e058a7155f73bf362a7b1babf7R34-R41): Added settings to configure schema …

Add support for loading schemas in service setup

---

.github/workflows/helm-lint.yml
deploy/templates/service-setup.yaml

This pull request includes changes to the GitHub Actions workflow and a Kubernetes YAML template. The most important changes are:
Workflow updates:
* [`.github/workflows/helm-lint.yml`](diffhunk://#diff-fb24acb876b6bfe365bb467eeb6196229cdc85ac6ea056eade9032f4b51e9baeR7): Added the `testing/v4` branch to the list of branches that trigger the `pull_request` event.
Kubernetes template adjustments:
* [`deploy/templates/service-setup.yaml`](diffhunk://#diff-9ce0a162b5f64bc5b7f641da3e8ec49cdd2f354d03b6cf8cc8718195a3c95f24L141-R141): Corrected the syntax by changing `{{- end -}}` to `{{ end }}` in the `VERBOSE` environment variable section.

Fix YAML syntax in service setup configuration

---

acs-admin/src/pages/AccessControl/Groups/GroupList.vue
acs-admin/src/pages/AccessControl/Groups/MembersTab.vue
acs-admin/src/pages/AccessControl/Groups/PermissionsTab.vue
acs-admin/src/pages/AccessControl/Permissions/EntriesDropdown.vue
acs-admin/src/pages/AccessControl/Permissions/EntriesTab.vue
acs-admin/src/pages/AccessControl/Permissions/GroupsTab.vue
acs-admin/src/pages/AccessControl/Permissions/PermissionList.vue
acs-admin/src/pages/AccessControl/Permissions/PermissionManagementSidebar.vue
acs-admin/src/pages/AccessControl/Permissions/PrincipalsTab.vue
acs-admin/src/pages/AccessControl/Permissions/entriesColumns.ts
acs-admin/src/pages/AccessControl/Principals/EffectivePermissionsTab.vue
acs-admin/src/pages/AccessControl/Principals/GroupsTab.vue
acs-admin/src/pages/AccessControl/Principals/PermissionsTab.vue
acs-admin/src/pages/AccessControl/Principals/PrincipalList.vue

Minor tweaks to provide a base sort so that the UI is predictable to a human eye.
Each table is now sorted by the `name` column, where that exists. Otherwise, it will be sorted by the first column, such as the Permission name.

Sort all tables within the Admin Auth UI

---

acs-edge-sync/lib/deployments.js

This prevents edge-sync from removing Flux's finalizers.
This was causing a bug where sometimes a HelmRelease resouce would be deleted but Flux would not uninstall the actual helm release; this was caused by the missing finalizer.
Fixes #457.

Restrict edge-sync to spec patching

---

acs-configdb/lib/model.js
acs-configdb/lib/notify.js
lib/js-rx-client/lib/configdb.js
lib/js-rx-client/lib/notify-v2.js
lib/js-rx-util/lib/util.js

* Support notify for `v2/class/:class/direct/*/`.
* Support this in RxClient.
* Fix a bug in RxClient when a notify request returns an error.
* Send a class update when we delete an object.

Support notify for direct class relations

---

acs-admin/src/store/useObjectStore.js
acs-admin/src/store/useStore.js

This PR introduces a generic store implementation that replaces our individual store implementations, reducing code duplication and providing a more flexible approach to data binding.
- Added new `useStore` factory function that creates reusable Pinia stores
- Stores are cached and reused across components
- Configurable class UUID watching
- Support for multiple app bindings with customizable keys
- Maintains all existing functionality of individual stores
```js
// Old way - individual store implementation for each type
const driverStore = useDriverStore()
// New way - generic store with configuration
const driverStore = useStore(
'driver',
UUIDs.Class.EdgeAgentDriver,
{ definition: UUIDs.App.DriverDefinition }
)()
```
- Always call the store function with `()` to initialize the Pinia …

Add generic store

---

acs-admin/src/main.js
acs-admin/src/store/serviceClientStore.js

The connection state of the client was stored in the Pina state. On page refresh, this state was reset causing a redirect to login because of a race condition between mounted() and router.beforeEach(). The client connection state is now stored in session storage to prevent this.

Fix Manager Auth Page Refresh

---

acs-service-setup/lib/manager-devices.js
acs-service-setup/lib/service-setup.js
lib/js-service-client/lib/uuids.js

This addition to service setup splits existing edge agent config into connection configuration and device information. The migration sets inserts the migration status into configDB to prevent the migration running after its initial run.

Manager migration from ConfigDB

---

acs-configdb/lib/model.js
acs-configdb/sql/migrate.sql
acs-configdb/sql/v11.sql

Add a property to _Object registration_ denoting that all our current classes have strict ranks. This is for future-compatibility if we allow mixed-rank or infinite-rank classes.

Be explicit about our strict-ranks restriction

---

acs-admin/vite.config.js

For some reason this is not sufficient to make `json-schema-ref-parser` bundle correctly, so we still need the in-tree copy. Probably with more tweaking we could fix this.

Fix Monaco editor in acs-admin build

---

acs-admin/src/App.vue
acs-admin/src/components/EdgeManager/Devices/OriginMapEditor/OriginMapEditor.vue
acs-admin/src/pages/EdgeManager/Devices/Device.vue

Minor tweaks within the Admin UI that allow for scrolling on long pages.
There are some whitespace changes (in individual commits) which I included as it helped me locate the right DOM node.
It's basically just a few `overflow-y-auto` added in with some `padding-bottom` to help complete it.

Fix bug preventing scrolling on the Admin UI

---

acs-admin/src/main.js
acs-admin/src/store/serviceClientStore.js

A router guard was semi-implemented, but disabled due to it malfunctioning.
The logic is now corrected and the user should be directed to the correct routes every time.
This still stores the user credentials in localStorage, this will be needed until other authentication mechanisms are in place.

Add router guard to Admin UI

---

acs-service-setup/dumps/edge.yaml

The edge-helm-charts build step ensures that this defaults correctly to the build registry. If we override here then non-GH builds don't work correctly.

Remove registry from driver registrations

---

acs-admin/Makefile
acs-admin/src/components/EdgeManager/Connections/NewConnectionDialog.vue

This pull request includes updates to `acs-admin`, focusing on build configuration and API request handling. The most notable changes involve switching to a different makefile for Docker builds and modifying HTTP request headers in the `NewConnectionDialog` component.
* [`acs-admin/Makefile`](diffhunk://#diff-a1524d6df5de19432e44ba241fd422dc99921c343ee7c2904d4a48e12f5896dfL7-R7): Replaced the inclusion of `acs.js.mk` with `acs.docker.mk` as the admin app uses `bun` and doesn't make use of the local build at all (and it was erroring).
* [`acs-admin/src/components/EdgeManager/Connections/NewConnectionDialog.vue`](diffhunk://#diff-8057c0cf5be2e3aaab1b826d5bf4d7d9801bcfa16bf23eff8bce8390d6a94c23L432-R435): Updated the HTTP request configuration to move the `Content-Type` definition from the …

Fix sealed secret Content-Type

---

acs-admin/src/store/useStore.ts
acs-admin/src/utils/edgeAgentConfigUpdater.js

* Internal drivers were being deployed as Driver due to not using the connection store.
* Connection detail updates were not being actioned.

Update connection details correctly

---

acs-admin/src/components/EdgeManager/Connections/NewConnectionDialog.vue

* `crypto.randomUUID` is only available in secure contexts.
* Carry through the node store change.

Fix sealed secret creation

---

acs-service-setup/lib/manager-devices.js

This change prevents @acs-service-setup from migrating devices that don't have a schema (where Schema_UUID is null or missing). Previously, the service would attempt to migrate all devices regardless of schema status, which could lead to issues with devices that lack proper schema information.
Changes:
- Added a check in the register_device method to verify Schema_UUID exists
- Added early return with logging when schema is missing or null
- Improved code organization by moving schema check earlier in the method
This ensures that only properly configured devices with valid schemas are migrated during the setup process.

Skip migration of devices without Schema_UUID

---

acs-admin/src/utils/edgeAgentConfigUpdater.js

This commit fixes an issue where Schema_UUID and Instance_UUID entries for nested objects in the originMap were not being consistently included in the generated edge agent configuration.
Changes:
- Modified processOriginMapObject in edgeAgentConfigUpdater.js to add Instance_UUID tags for metric objects (with Sparkplug_Type)
- Added handling for both Schema_UUID and Instance_UUID in non-metric nested objects
- Ensures all levels of the originMap hierarchy properly include both Schema_UUID and Instance_UUID in the generated configuration
This ensures that device configurations correctly maintain object identity and type information through both Schema_UUID and Instance_UUID at all levels of nesting, not just at the root level.

Add Schema_UUID and Instance_UUID tags for all nested objects in edge agent config

---

acs-admin/README.md
acs-admin/docs/developer-guide.md

This PR adds developer documentation for ACS Admin to improve the onboarding experience for new developers. The documentation provides a comprehensive guide to the architecture, technology stack, and development patterns used in the application.
- Create detailed developer guide (`docs/developer-guide.md`) covering:
- Architecture overview and key concepts
- Technology stack and project structure
- Store system and Factory+ integration
- UI components and authentication
- Guidelines for adding new features
- Testing and deployment information
- Update `README.md` to link to the new developer guide
- Maintain existing `useStore.md` documentation
Comprehensive documentation is essential for onboarding new developers and ensuring consistent development practices. This PR addresses the need …

Add developer documentation for ACS Admin

---

acs-service-setup/lib/auth-group.js

Without this we will resurrect removed group memberships on helm upgrade.

Clear old auth groups when they are migrated

---

acs-service-setup/dumps/edge.yaml

This pull request makes updates to the `acs-service-setup/dumps/edge.yaml` file to fix the modbus driver.
* Added path (which must be 0)
* Added the missing `protocol` field with a default value of `tcp`.

Add missing protocol option to modbus driver definition

---

acs-admin/src/components/EdgeManager/Connections/NewConnectionDialog.vue
acs-admin/src/components/EdgeManager/Devices/ChangeConnectionDialog.vue

Make the connection selector use the `edgeAgent` UUID instead of mis-matched topology key from migration/connection creation.

Fix connection selector

---

acs-files/bin/api.js
acs-files/lib/api-v1.js
acs-files/lib/parseSize.js
acs-files/lib/startup.js
acs-files/package-lock.json
acs-files/package.json
acs-service-setup/dumps/files.yaml
deploy/values.yaml

ACS File Service used fs.writeFile to write files which buffers them to memory before writing. The file service now uses fs.createWriteStream to write the file to the Kubernetes volume.

Fix high memory usage when writing large files

---

acs-admin/src/components/ObjectSelector/ObjectSelector.vue
acs-admin/src/components/ui/data-table-searchable/DataTableSearchable.vue

The button was looking for a default slot which has been removed.
The button now gets placed within the toolbar-right slot.
Other minor details have been re-included (how many elements are showing with the current filter).
This issue prevents users from changing members/subclasses in ConfigDB UI as well as updating groups and permissions in the Auth UI.
This fix gets that functionality working again.

Fix missing confirm button on ObjectSelector

---

.github/workflows/js-lib.yaml
.github/workflows/publish.yml
.github/workflows/release.yaml

Change the GH actions to support publishing the in-tree JS libs to NPM. Support this using release tags of the form `js/lib-name/vN.N.N` and a new top-level workflow to choose which form of release this is. The existing release workflow no longer runs on `release` but on `workflow_call`.

Allow publishing JS libs to NPM

---

.github/workflows/publish.yml
.github/workflows/release.yaml

I don't fully understand how this permission was available before when it isn't declared in the job step, but maybe the top-level workflow just gets all permissions.

Releasing the Helm Chart needs contents: write

---

lib/js-service-client/lib/service/files.js

The error now throw the status returned from the fetch on upload file.

Add missing files interface error status

---

edge-ads/lib/ads.js

Previously the registration of the connect and disconnect handlers were in the connect method, meaning that every time the driver reconnected it re-registered them, resulting in a snowball effect when things like the PLC program were changed.

Move event registration to constructor in ADS driver
