AMRC-FactoryPlus/amrc-connectivity-stack

- README.md
* Document the process of upgrading and ACS install.
* Document that major versions may require manual steps and must not be skipped.
* Document the process of installing from a Git checkout.
> Updates to the README.

- templates/configdb/configdb.yaml
- templates/directory/directory-mqtt.yaml
- templates/directory/directory-webapi.yaml
- values.yaml
* Publish an internal URL for the ConfigDB. Allow the Directory to make it external as needed.
* Pull a new Directory version to fix https externals.
> Start working towards multiple baseUrls.

- values.yaml
The values.yaml file was modified to update the Manager component version from v1.0.5 to v1.0.6. This update is important to include recent features and bug fixes from the latest version.
> Update Manager component version to v1.0.6

- templates/dumps.yaml
- templates/manager/env/manager-config.yaml
This PR
- Updates the required environment variables for the manager to support V3
- Removes the old `manager` role and applies more restrictive permissions for selected ConfigDB apps
> Manager changes

- templates/identity/kdc.yaml
- values.yaml
Cherry-picked from fb7cb98441313ff76e0f66fde86d51e374831304.
> Allow modifications to the kadmin ACL

- templates/_helpers.tpl
This is needed by the Postgres change.
> Backport image-name template from main

- templates/auth/auth.yaml
- templates/configdb/configdb.yaml
- templates/dumps.yaml
- templates/manager/database/database.yaml
- templates/manager/manager.yaml
- templates/manager/meilisearch.yaml
- templates/manager/redis.yaml
- templates/postgres/postgres.yaml
- templates/support/kubegres/kubegres.yaml
- values.yaml
* Allow all images used to be customised.
* Allow imagePullSecrets to be specified in the values file.
* Allow imagePullPolicy to be set for the Manager images.
* Update default Postgres version to 16.1.
This includes the changes from #97 by @derme302.
> Improve image handling

- values.yaml
(cherry picked from commit d975fc10edc2a5178c9f340403388da945f3f6a4)
> Disable PDB for InfluxDB deployment

- templates/cmdesc/cmdesc.yaml
- templates/directory/directory-mqtt.yaml
- templates/directory/directory-webapi.yaml
- templates/identity/kdc.yaml
- templates/identity/krb-keys-operator.yaml
- templates/manager/cron.yaml
- templates/manager/manager.yaml
- templates/manager/queue.yaml
- templates/manager/schema-import-cron.yaml
- templates/mqtt/mqtt.yaml
- templates/warehouse/influxdb-ingester.yaml
This is needed for offline cluster scenarios.
> Include pullSecrets on all images

- values.yaml
(cherry picked from commit 15a6bce45c73fdfdb2feb537620633fbf2a9a3c4)
> Update InfluxDB ingester to v1.2.1

- acs-edge/lib/helpers/typeHandler.ts
- acs-edge/lib/sparkplugNode.ts
- acs-edge/lib/uuids.ts
* Generate V5 UUIDs for Alerts.
* Fix JSON path handling.
> Edge Agent changes moved over from acs-edge

- deploy/templates/dumps.yaml
This is quite a broad grant of permissions, but krbkeys has effective root permissions anyway simply by virtue of its function.
> Give krbkeys permission to edit accounts

- acs-service-setup/dumps/helm.yaml
- deploy/templates/dumps.yaml
* Update the HelmRelease template to request CRD replacement.
* Remove some redundant permission grants.
> Installation changes

- acs-cluster-manager/Makefile
- acs-cluster-manager/lib/checkout.js
- acs-cluster-manager/package.json
- acs-git/lib/auto-pull.js
- acs-git/lib/git-server.js
- acs-git/lib/status.js
- acs-git/package.json
- acs-service-setup/package.json
We have created a fork of isomorphic-git as we need an urgent bug fix. Move to using this.
> Move to our fork of isomorphic-git

- acs-edge/lib/sparkplugNode.ts
- acs-edge/lib/translator.ts
Commit bcad293 introduced a bug in that it was trying to await in a constructor. Refactor to avoid this.
> Fix await error in the Edge Agent

- acs-edge/lib/helpers/sparkplug.ts
- acs-edge/lib/helpers/typeHandler.ts
- acs-edge/lib/sparkplugNode.ts
- acs-edge/lib/translator.ts
Publish a folder of metrics in our NBIRTH which includes all metrics available on all devices. These metrics are never updated in NDATA, they are just there to advertise metrics we can collect but are not necessarily collecting yet.
> Publish available metrics in Edge Agent NBIRTH

- acs-auth/bin/sexpr.js
- acs-auth/docs/redesign.md
- acs-auth/docs/redesign/dyn-groups.md
- acs-auth/docs/redesign/sexpr.md
- acs-rendezvous/docs/NOTES.md
- acs-rendezvous/docs/notify-v1.md
It is clear that the current Auth data model is not sufficient for a dynamic environment.
* Document the current problems.
* Give requirements for dynamic deployments.
* Spec two possible solutions.
> Look into possibilities for an enhanced Auth service

- acs-edge/.dockerignore
- acs-edge/package-lock.json
- acs-edge/package.json
Force npm to use `@types/readable-stream` v4.0.11.
> Fix Edge Agent build problems

- edge-modbus/bin/driver.js
- edge-modbus/lib/modbus.js
- edge-modbus/package-lock.json
- edge-modbus/package.json
- edge-test/Makefile
- edge-test/bin/driver.js
- edge-test/lib/test.js
- edge-test/package-lock.json
- edge-test/package.json
This version creates the handler using a static class method rather than a factory function, and handles reconnecting when the connection drops.
> Update modbus and test drivers to new library

- acs-visualiser/package-lock.json
- acs-visualiser/public/mqttclient.js
- acs-visualiser/public/packet.js
- acs-visualiser/public/vis.js
Display a node for each command source and make these nodes fade out after 7.5s.
> Show source nodes for commands

- .github/workflows/publish.yml
- edge-helm-charts/Dockerfile
- edge-helm-charts/charts/edge-agent/values.yaml
- edge-helm-charts/charts/edge-cluster/values.yaml
- mk/acs.docker.mk
Now we have a build step for the edge-helm-charts updating the tag is straightforward.
> Automatically update edge chart image tags

- edge-modbus/lib/modbus.js
- edge-modbus/package-lock.json
- edge-modbus/package.json
- edge-test/package-lock.json
- edge-test/package.json
This version supports callback APIs as well as Promise APIs.
> Update edge drivers to v0.0.4 of the library

- ContributorGuidelines.md
- README.md
Created contributor guidelines for consistency and to encourage quality contributions to the project.
> Add Contributor guidelines

- acs-configdb/editor/editor.js
- acs-configdb/editor/index.html
- acs-configdb/lib/api-v1.js
- acs-configdb/lib/api-v2.js
- acs-configdb/lib/model.js
- acs-configdb/lib/notify.js
- acs-configdb/lib/special.js
- acs-configdb/package-lock.json
- acs-configdb/package.json
- acs-configdb/sql/grant.sql
- acs-configdb/sql/v8.sql
- acs-configdb/sql/v9.sql
- mk/acs.k8s.mk
* Add API endpoints to edit members and subclasses of a class.
* Support PATCH to the _Object registration_ entry.
* Start working on `/editor` support. This is usable but not complete.
* Support a notify interface for class membership.
> Support editing of class membership

- edge-bacnet/package-lock.json
- edge-bacnet/package.json
- edge-modbus/package-lock.json
- edge-modbus/package.json
- edge-test/package-lock.json
- edge-test/package.json
- edge-tplink-smartplug/package-lock.json
- edge-tplink-smartplug/package.json
This fixes a bug in the PolledDriver.
> Update edge driver library

- acs-manager/app/Domain/Devices/Actions/ConfigureDeviceAction.php
- acs-manager/app/Domain/Devices/Actions/DeleteDeviceAction.php
- acs-manager/app/Domain/Devices/Actions/UpdateDeviceInformationAction.php
- acs-manager/app/Domain/Schemas/Actions/ImportSchemasFromStorageAction.php
- acs-manager/app/Http/Controllers/DeviceController.php
- acs-manager/docker-compose.yml
- acs-manager/resources/js/components/Containers/NodeContainer.vue
- acs-manager/routes/api.php
This PR adds the ability to import existing node configurations into a node.
**Features**:
- Selective import
- Merging of connections
- Preserves `Instance_UUIDs`
> Import devices to manager

- acs-admin/Dockerfile
> Pin admin build image to oven/bun:1.2.0

- acs-krb-keys-operator/lib/amrc/factoryplus/krbkeys/keyops.py
- Updated the calculation of key replacement times to ensure correctness.
- Added logic to track when each key version (KVNO) stops being the most recent, using the timestamp of the next higher KVNO.
- Defaulted keys with no replacements to "active" by assigning `float('inf')` as their replacement time.
- This ensures expired keys are removed based on accurate replacement timestamps rather than only their creation times.
This fix prevents premature removal of keys that may still be in use or valid until replaced by newer versions.
> Fix key replacement logic in keytab trimming

- acs-edge-sync/lib/nodes.js
- acs-krb-keys-operator/lib/amrc/factoryplus/krbkeys/account.py
- acs-service-setup/lib/clusters.js
- acs-service-setup/lib/helm.js
- acs-service-setup/lib/service-config.js
- lib/js-service-client/lib/service/auth.js
- lib/js-service-client/lib/service/service-interface.js
Misc fixes required to get the edge services working again.
> Fix edge services

- .github/workflows/publish.yml
- .gitignore
- acs-edge/lib/device.ts
- acs-edge/lib/devices/driver.ts
- acs-edge/lib/driverBroker.ts
- acs-edge/lib/helpers/typeHandler.ts
- acs-edge/lib/sparkplugNode.ts
- edge-openprotocol/.env.example
- edge-openprotocol/.gitignore
- edge-openprotocol/Dockerfile
- edge-openprotocol/Makefile
- edge-openprotocol/bin/driver.js
- edge-openprotocol/lib/openprotocol.js
- edge-openprotocol/package-lock.json
- edge-openprotocol/package.json
This requires version 0.1.0 of the `js-edge-driver`, which wasn't published at the time of this PR.
> Add OpenProtocol Driver

- deploy/templates/files/files.yaml
- deploy/templates/files/ingress.yaml
- deploy/values.yaml
The images don't exist yet but this gives a framework for development.
> Deploy the File service

- acs-cmdesc/package-lock.json
- acs-cmdesc/package.json
- acs-configdb/package-lock.json
- acs-configdb/package.json
- acs-directory/.gitignore
- acs-directory/package-lock.json
- acs-directory/package.json
Where we depend on `utilities@2.0.0`, fix `service-client@1.3.4` and commit a package-lock to ensure this is respected in the Docker build.
> Fix service-client/utilities compat issue

- docs/edge-scout.md
updated design spec to reflect the removal of validateConfigDetails from DeviceConnection abstract class.
> Scout Design Spec update 

- acs-admin/src/store/useStore.js
- acs-admin/src/store/useStore.ts
This PR extends our generic store implementation with support for nested app bindings and converts the core store logic to TypeScript. This enhancement allows stores to watch not just direct ConfigDB app entries, but also follow references within those entries to other apps, creating a chain of reactive bindings.
The store system watches ConfigDB entries and creates reactive bindings. With nested bindings, it can:
1. Watch a primary ConfigDB app entry
2. Extract UUIDs from specific fields in that entry
3. Automatically watch the referenced ConfigDB apps
4. Make all this data available reactively in the store
```js
// Simple binding - watches a single app
// Here, when objects of class EdgeAgentDriver are created/updated/deleted,
// their corresponding entries in DriverDefinition app are …
```
> Enhanced Store Implementation with Nested App Bindings and TypeScript Migration

- .github/workflows/publish.yml
- Makefile
- acs-files/.dockerignore
- acs-files/eslint.config.mjs
- acs-files/package-lock.json
- acs-files/package.json
Adds acs-files to the acs build process.
> Add acs-files to build

- acs-admin/src/pages/EdgeManager/EdgeClusters/EdgeCluster.vue
- acs-admin/src/pages/EdgeManager/EdgeClusters/nodeColumns.ts
- acs-admin/src/pages/EdgeManager/Nodes/Node.vue
This also fixes some missed references to the new nodeStore.
> Refactor EdgeCluster and Node components to use optional chaining

- acs-admin/src/components/ui/data-table-searchable/DataTableSearchable.vue
- acs-admin/src/pages/ConfigDB/Applications/ApplicationList.vue
- acs-admin/src/pages/ConfigDB/ConfigDB.vue
- acs-admin/src/pages/ConfigDB/Objects/ObjectList.vue
- acs-admin/src/pages/ConfigDB/Objects/ObjectPage.vue
A few small UI tweaks to the ConfigDB component. I was aiming to add breadcrumbs like we have in the edge manager pages but didn't get around to it.
> Improve UI of ConfigDB Component

- acs-git/bin/git-server.js
- acs-git/lib/auto-pull.js
- deploy/templates/git/git.yaml
- docs/services/git-auth.md
- docs/services/git-server.md
This PR adds support for authenticating with private external Git repositories in the ACS Git mirroring functionality. The implementation uses Kubernetes secrets to securely store and access credentials, allowing ACS to mirror private repositories from external sources.
- **Authentication Configuration**: Added an `auth` property to the `PullSpec` class to store authentication configuration from the Git repository configuration.
- **Secret Management**: Implemented methods to read and parse credentials from Kubernetes secrets, with support for both JSON and simple `username:password` formats.
- **Authentication Logic**: Modified the Git fetch operation to use credentials when specified, with proper error handling and credential caching.
- **Kubernetes Integration**: Updated the Kubernetes …
> Add secret-based authentication for external Git repositories

- docs/services/file-service.md
- Add PUT /v1/file/:uuid endpoint docs.
- Mark POST /v1/file endpoint as removed.
> Update ACS-Files Docs

- acs-configdb/lib/routes.js
- lib/js-service-api/lib/webapi.js
This way it can respect the body limit.
> Move registration of JSON merge patch to `js-service-api`

- deploy/templates/hooks/post-delete.yaml
- deploy/templates/service-setup.yaml
- deploy/values.yaml
Bitnami have removed most of their freely-available images.
> Update kubectl image
